# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titel')),
                ('body', redactor.fields.RedactorField(verbose_name='Tekst')),
            ],
        ),
    ]
