# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 20:06
from __future__ import unicode_literals

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.PathAndRename('cover-photos')),
        ),
        migrations.AddField(
            model_name='article',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='lead',
            field=models.CharField(default='Lead', max_length=512, verbose_name='Manchet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
