# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160811_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='downs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='rank',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='ups',
            field=models.FloatField(default=0),
        ),
    ]
