# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160815_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='downs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='ups',
            field=models.IntegerField(default=0),
        ),
    ]
