# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-01 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160825_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default=2, max_length=1028, verbose_name='kilde'),
            preserve_default=False,
        ),
    ]
